model:
  type: FR_UNet
  args:
    {}

loss:
  type: BCELoss
  args:
    {}

optimizer:
  type: Adam
  args:
    lr: 1e-4
    weight_decay: 1e-5

warmup_epochs: 10
min_lr: 1e-7
lr: 1e-4
epochs: 40
save_dir: saved/
val_per_epochs: 1
save_period: 1
tensorboard: true
threshold: 0.5
threshold_low: 0.3
DTI: false
tta: false
CCC: false